config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :profiles
  resources :homes

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root to: 'homes#index'
  resources :users do
    get :create_friend_request, on: :member
    get :destroy_friend_request, on: :member
    get :accept_friend_request, on: :member
    get :remove_friend, on: :member
    get :index_friends, on: :collection
    resources :chats
  end

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :messages, only:[:create]
end

app/models/user.rb
class User < ApplicationRecord

  self.include_root_in_json = false
  include Tire::Model::Search
  include Tire::Model::Callbacks


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  before_create :build_default_profile
  after_touch() { tire.update_index }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :nickname, presence: true

  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  has_friendship


  mapping do
    indexes :nickname, type: 'string'
    indexes :profile do
      indexes :firstname, type: 'string'
      indexes :secondname, type: 'string'
    end
  end


  def to_indexed_json
    to_json( include: { profile: { only: [:firstname, :secondname] } } )
  end


  private
    def build_default_profile
      build_profile
      true
    end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end


  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :attribute])
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [:index, :index_friends]

  def index
    if params[:q].present?
      @users = User.search(params[:q], load: true)
    else
      @users = User.all.order(created_at: :desc)
    end
  end


  def show
    @posts = @user.posts.order(created_at: :desc)
  end


  def create_friend_request
    current_user.friend_request(@user)
    flash[:notice] = 'Request Send'
    redirect_to user_path(@user)
  end


  def destroy_friend_request
    current_user.decline_request(@user)
    flash[:alert] = 'Request Destroy'
    redirect_to user_path(@user)
  end


  def accept_friend_request
    current_user.accept_request(@user)
    flash[:notice] = 'Friend Added'
    redirect_to user_path(@user)
  end


  def remove_friend
    current_user.remove_friend(@user)
    flash[:alert] = 'Friend Deleted'
    redirect_to user_path(@user)
  end


  def index_friends
    @myfriends = current_user.friends
    @myrequests = current_user.requested_friends
  end

  private
    def set_user
      @user  = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friendbutton.html.haml
- if @user.id == current_user.id
  %a.edit-profile
    %a.edit-profile{href: edit_profile_path(current_user.profile)}
      %button{class: 'btn btn-outline-primary btn-sm'} Edit Profile

- else
  - if current_user.friends.include? @user
    %a.edit-profile{ href: remove_friend_user_path }
      %button{class: 'btn btn-outline-primary btn-sm'} Friend
  - else
    - if current_user.pending_friends.include? @user
      %a.edit-profile{ href: destroy_friend_request_user_path }
        %button{class: 'btn btn-outline-primary btn-sm'} Request Send

    - if current_user.requested_friends.include? @user
      %a.edit-profile{ href: accept_friend_request_user_path }
        %button{class: 'btn btn-outline-primary btn-sm'} Accept Request

    - if (!current_user.pending_friends.include? @user) && (!current_user.requested_friends.include? @user)
      %a.edit-profile{ href: create_friend_request_user_path }
        %button{class: 'btn btn-outline-primary btn-sm'} Add Friend

app/views/users/index.html.haml
.container.text-center
  - @users.each do |user|
    .users-show.row
      .col-md-5
        .user
          .avatar
            - if user.profile.photo?
              = link_to user_path(user) do
                = image_tag user.profile.photo_url
          = link_to user.nickname, user_path(user), class: 'username'

app/views/users/index_friends.html.haml
.text-center
  %h5 My friends
  .card-group
    - @myfriends.each do |myfriend|
      .container.text-center{ style:  'width: 350px;' }
        .card.shadow.p-3.mb-5.bg-white.rounded{style: "margin: 15px;"}
          = link_to user_path(myfriend) do
            %img.card-img-top{src: myfriend.profile.photo, style: 'height: 200px; width: auto'}
          .card-body
            %p.card-text
              = myfriend.nickname


.text-center
  %h5 Requests
  - @myrequests.each do |myrequest|
    .container.text-center{ style:  'width: 350px;' }
      .card.shadow.p-3.mb-5.bg-white.rounded{ style: "margin: 15px;" }
        = link_to user_path(myrequest) do
          %img.card-img-top{src: myrequest.profile.photo}
        .card-body
          %p.card-text
            = myrequest.nickname

app/views/users/show.html.haml
.card.mb-3.mx-auto{ style: "max-width: 1500px;" }
  .row.no-gutters
    .col-md-4
      - if @user.profile.photo?
        = image_tag @user.profile.photo_url(:thumb), class: 'card-img-left rounded', style: 'height: 300px; width: auto;'
    .col-md-8
      .card-body
        .card-title.d-flex.justify-content-between.align-items-between
          %h5{class: 'font-italic'} @ #{@user.nickname}

          %ul
            %span{ class: 'font-weight-bold' }
              #{@user.posts.count}
            %small.text-muted{ style: "margin-right: 15px;" } posts

            %span{ class: 'font-weight-bold' }
              #{@user.friends.count}
            %small.text-muted{ style: "margin-right: 15px;" } friends

            %span{ class: 'font-weight-bold' }
              #{@user.requested_friends.count}
            %small.text-muted{ style: "margin-right: 15px;" } following

          = render 'friendbutton'

        %p.card-text
          %br
          - if @user.profile.firstname? && @user.profile.secondname?
            %h2.name= @user.profile.firstname + ' ' + @user.profile.secondname
            .about{class: 'font-weight-lighter'}= @user.profile.about


.user-tabs
  %a.tab.active{href: '#'}
    Posts
  %a.tab{href: '#'}
    Liked
  %a.tab{href: '#'}
    Saved
%br


.d-flex.justify-content-between.align-items-between{style: 'display: flex; width: auto; height: auto; flex-flow: row wrap;'}
  - @posts.each do |post|
    .container.card.shadow.p-3.mb-5.bg-white.rounded{style: 'width: auto; margin-left: 50px;'}
      = link_to post_path(post) do
        = image_tag post.image, style: 'height: 200px; width: auto'