config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :profiles
  resources :homes

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root to: 'homes#index'
  resources :users do
    get :create_friend_request, on: :member
    get :destroy_friend_request, on: :member
    get :accept_friend_request, on: :member
    get :remove_friend, on: :member
    get :index_friends, on: :collection
    resources :chats
  end

  resources :posts do
    resources :likes
    resources :comments
  end

  resources :messages, only:[:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: true, case_sensitive: false

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, allow_blank: false
  validates :user_id, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  validates :content, presence: true

  after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validate :image_presence

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user, touch: true

  User.tire.index.refresh


  mount_uploader :photo, PhotoUploader
  serialize :photo, JSON
end

app/models/subscription.rb
class Subscription < ApplicationRecord

  belongs_to :chat
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  self.include_root_in_json = false
  include Tire::Model::Search
  include Tire::Model::Callbacks


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  before_create :build_default_profile
  after_touch() { tire.update_index }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :nickname, presence: true

  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  has_friendship


  mapping do
    indexes :nickname, type: 'string'
    indexes :profile do
      indexes :firstname, type: 'string'
      indexes :secondname, type: 'string'
    end
  end


  def to_indexed_json
    to_json( include: { profile: { only: [:firstname, :secondname] } } )
  end


  private
    def build_default_profile
      build_profile
      true
    end



end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :authenticate_user!

  def index
    @chats = current_user.chats
    @myfriends = current_user.friends
  end


  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat, other_user: @other_user.id)
  end


  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end


  def destroy
    @chat = Chat.find_by(id: params[:id])
    @chat.destroy
    redirect_to user_chats_path
  end

  private
    def find_chat(second_user)
      chats = current_user.chats
      chats.each do |chat|
        chat.subscriptions.each do |s|
          if s.user_id == second_user.id
            return chat
          end
        end
      end
      nil
    end




end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :find_post
  before_action :find_like, only: [:destroy]


  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end

    respond_to do |format|
      format.js { render 'posts/show.js.erb' }
      format.html { redirect_to post_path(@post) }
    end
  end


  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end


  private
    def find_post
      @post = Post.find(params[:post_id])
    end

    def already_liked?
      Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end

    def find_like
      @like = @post.likes.find(params[:id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
    @comments = @post.comments

  end


  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to user_path(current_user)
  end



  private
  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.haml
.container.text-center
  %br
  %br
  All Users:
  %br
  %br
  - User.all.each do |other_user|
    - if other_user != current_user
      = link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do
        = other_user.nickname
        %br

app/views/chats/show.html.haml
.container

  = link_to 'Delete chat', user_chat_path(current_user, @chat, other_user: @other_user.id), method: :delete, data: { confirm: 'Delete chat?'}, class: 'btn btn-outline-danger'
  %br
  %br

  %br
  = render partial: 'messages/message_form', locals: {message: @message, chat: @chat}
  .card
    .card-header
      Chat with @#{@other_user.nickname}
    .card-body
      %blockquote.blockquote.mb-0

        #chatbox
          = render partial: 'messages/message', collection: @chat.messages.order(created_at: :desc)

app/views/homes/index.html.haml
!!!

= yield


.container.mx-auto{:style => "width: 650px;"}

  - @posts.each do |post|

    .card-header{:style => "width: 600px;"}
      = link_to user_path(post.user), {style: 'color:#262626;'} do
        %img{ src: post.user.profile.photo_url, height: '30px', width: 'auto'}
        = post.user.nickname

    .card{:style => "width: 600px;"}
      = link_to post_path(post) do
        = image_tag post.image, class: 'card-img-top'


      .card-body
        %p.card-text
          .d-flex.justify-content-between.align-items-between
            .text-md
              = post.description
            .text-muted
              = post.likes.count
              %i.fas.fa-heart
              = post.comments.count
              %i.fas.fa-comment-alt
    %br
      %br

app/views/posts/_likebutton.html.haml
- pre_like = @post.likes.find { |like| like.user_id == current_user.id }
- if pre_like
  = link_to 'Unlike', post_like_path(@post, pre_like), remote: true, method: :delete, class: 'btn btn-outline-dark'
- else
  = link_to 'Like', post_likes_path(@post), remote: true, method: :post, class: 'btn btn-outline-dark'

app/views/posts/_likescount.html.haml
= @post.likes.count
%i.fas.fa-heart
= @post.comments.count
%i.fas.fa-comment-alt

app/views/posts/new.html.haml
.container.mx-auto{:style => "width: 600px;"}
  = form_for Post.new do |f|
    .input-group
      .input-group-prepend
        %span.input-group-text Description
        = f.text_area :description, class: 'form-control', size: '40x4'
    .formfile
      = f.file_field :image, :onchange => "readURL(this)"
    .actions
      %br
      = f.submit 'Create post', class: 'btn btn-outline-dark'
      %br
      %br
    .rounded.mx-auto{:style => "width: 100%;"}
      %img#img_prev{height: '350px', width: 'auto', class: 'shadow p-3 mb-5 bg-white rounded'}

    .form-group
      = f.text_field :user_id, value: current_user.id, class:'d-none'

app/views/posts/show.html.haml
.mx-auto{:style => "width: 600px;"}
  .container
    .col-md-4
      .card.mb-4.shadow-sm{:style => "width: 503px;"}
        .card-header
          = link_to @post.user.nickname, user_path(@post.user), {style: 'color: gray;'}
        %svg.bd-placeholder-img.card-img-top{"aria-label" => "Placeholder: Thumbnail", :focusable => "false", :height => "0", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "100%"}
          .mx-auto.my-auto
            = image_tag @post.image, {:style => "width: 500px; height: auto;"}
        .card-body

          %p.card-text.font-weight-lighter
            = @post.description
          .d-flex.justify-content-between.align-items-center

            .btn-group
              .btn-outline-secondary{:style => "margin-right: 10px;"}
                #likebutton
                  = render 'likebutton'

              .btn-outline-secondary{:style => "margin-right: 10px;"}
                =link_to 'Comment', new_post_comment_path(@post), method: :get, class: 'btn btn-outline-dark'

              .btn-outline-secondary
                - if current_user == @post.user
                  = link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-dark'


            .text-muted#likes
              = render 'likescount'

= render @post.comments

app/views/posts/show.js.erb
var likes = document.querySelector("#likes");

likes.innerHTML = "<%= j render partial: 'posts/likescount' %>";


var likebutton = document.querySelector("#likebutton");

likebutton.innerHTML = "<%= j render partial: 'posts/likebutton' %>";